<div class="min-h-screen bg-[#F8FAFC]">
  {{-- CardapioPublico.tsx convertido: abas usam JS puro e pratos usam @foreach. --}}
  <div class="relative h-48 bg-cover bg-center" style="background-image:url('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&h=400&fit=crop')"><div class="absolute inset-0 bg-gradient-to-b from-[#0F172A]/70 to-[#0F172A]/50"></div></div>
  <div class="relative z-10 mx-auto -mt-20 max-w-6xl px-4 pb-12 sm:px-6 lg:px-8">
    <section class="mb-8 rounded-xl bg-white p-6 text-center shadow-lg md:p-8"><div class="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-full border-4 border-white bg-[#DC2626] text-3xl shadow-lg">🍽️</div><h1 class="font-display mb-3 text-3xl font-bold md:text-4xl">{{ $restaurant['name'] }}</h1><p class="mb-6 text-lg text-[#64748B]">{{ $restaurant['description'] }}</p><div class="grid gap-4 text-sm md:grid-cols-3"><span class="text-[#64748B]">📍 {{ $restaurant['address'] }}</span><span class="text-[#64748B]">☎ {{ $restaurant['phone'] }}</span><span class="text-[#64748B]">🕒 {{ $restaurant['hours'] }}</span></div><div class="mt-6 flex flex-wrap justify-center gap-6 border-t border-[#E2E8F0] pt-6 text-sm text-[#64748B]"><a href="https://instagram.com/{{ ltrim($restaurant['instagram'], '@') }}" target="_blank">{{ $restaurant['instagram'] }}</a><a href="https://facebook.com/{{ $restaurant['facebook'] }}" target="_blank">{{ $restaurant['facebook'] }}</a><a href="https://{{ $restaurant['website'] }}" target="_blank">{{ $restaurant['website'] }}</a></div></section>
    <div data-menu-tabs class="sticky top-0 z-20 mb-6 overflow-x-auto rounded-xl bg-white p-2 shadow-md"><div class="flex gap-2">@foreach($categories as $category)<button data-menu-tab="category-{{ $category['id'] }}" class="whitespace-nowrap rounded-lg px-6 py-3 font-medium transition-colors {{ $loop->first ? 'bg-[#DC2626] text-white' : 'text-[#64748B] hover:bg-[#F8FAFC]' }}">{{ $category['name'] }}</button>@endforeach</div></div>
    @foreach($categories as $category)
      <section data-menu-panel="category-{{ $category['id'] }}" class="{{ $loop->first ? '' : 'hidden' }}"><h2 class="font-display mb-6 text-2xl font-bold">{{ $category['name'] }}</h2><div class="grid gap-6 md:grid-cols-2">@foreach($category['dishes'] as $dish)<article class="overflow-hidden rounded-xl border border-[#E2E8F0] bg-white shadow-sm transition-shadow hover:shadow-md"><div class="relative"><img src="{{ $dish['image'] }}" alt="{{ $dish['name'] }}" class="h-48 w-full object-cover">@if($dish['featured'])<span class="absolute right-3 top-3 rounded-full bg-[#F59E0B] px-3 py-1 text-sm font-medium text-white">Destaque</span>@endif</div><div class="p-5"><div class="mb-2 flex items-start justify-between gap-4"><h3 class="flex-1 text-lg font-medium">{{ $dish['name'] }}</h3><span class="font-display text-xl font-bold text-[#DC2626]">R$ {{ number_format($dish['price'], 2, ',', '.') }}</span></div><p class="text-sm text-[#64748B]">{{ $dish['description'] ?? 'Descrição do prato pronta para ser editada no painel administrativo.' }}</p></div></article>@endforeach</div></section>
    @endforeach
  </div>
</div>
